FROM golang:1.24.4-alpine

WORKDIR /cloudmesh

COPY go.mod go.sum ./

RUN go mod download && go mod verify

RUN go install github.com/air-verse/air@latest

COPY . .

ENV APP_TYPE=api

ENTRYPOINT ["sh", "-c", "air -c .air.${APP_TYPE}.toml"]
