services:
  cloudmesh_backend:
    image: blackmamoth/cloudmesh_backend:stag-latest
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.1"
          memory: "64M"
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        max_failure_ratio: 0.3
      rollback_config:
        order: start-first
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 30s
        max_failure_ratio: 0.3
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 60s
    volumes:
      - ./oauth.config.yml:/oauth.config.yml
    networks:
        - cloudmesh
    env_file:
        - .env
    ports:
        - 8080:8080
    environment:
      POSTGRES_HOST: cloudmesh_db
      HOST: 0.0.0.0
    healthcheck:
      test: "wget --no-verbose --spider http://localhost:8080 || exit 1"
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      - cloudmesh_db

  db:
    image: postgres:16-alpine
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cloudmesh" ]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ${PWD}/pgdata:/var/lib/postgresql/data
    networks:
        - cloudmesh

networks:
  cloudmesh:
    external: true
