
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cloudmesh_backend
    restart: always
    ports:
      - 8080:8080
    dns:
      - 1.1.1.1
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      HOST: 0.0.0.0
    volumes:
      - ./:/cloudmesh
    healthcheck:
      test: [ "CMD-SHELL", "wget", "--spider", "http://localhost:8080/ping" ]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    container_name: cloudmesh_database
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cloudmesh" ]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ${PWD}/pgdata:/var/lib/postgresql/data
