google:
  client_id: ${GOOGLE_CLIENT_ID}
  client_secret: ${GOOGLE_CLIENT_SECRET}
  callback_url: http://localhost:8080/v1/api/auth/google/callback 
  scopes:
    - https://www.googleapis.com/auth/userinfo.email
    - https://www.googleapis.com/auth/userinfo.profile
    - openid
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.file
    - https://www.googleapis.com/auth/drive.metadata.readonly
      
dropbox:
  client_id: ${DROPBOX_CLIENT_ID}
  client_secret: ${DROPBOX_CLIENT_SECRET}
  callback_url: http://localhost:8080/v1/api/auth/dropbox/callback
  scopes:
    - files.metadata.read
    - files.content.write
    - files.content.read
    - file_requests.read
