// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: synced_items.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type AddSyncedItemsParams struct {
	AccountID      pgtype.UUID        `json:"account_id"`
	ProviderFileID string             `json:"provider_file_id"`
	Name           string             `json:"name"`
	Extension      string             `json:"extension"`
	Size           int64              `json:"size"`
	Path           pgtype.Text        `json:"path"`
	MimeType       pgtype.Text        `json:"mime_type"`
	ParentFolder   pgtype.Text        `json:"parent_folder"`
	IsFolder       bool               `json:"is_folder"`
	IsTrashed      pgtype.Bool        `json:"is_trashed"`
	OwnerInfo      json.RawMessage    `json:"owner_info"`
	ContentHash    pgtype.Text        `json:"content_hash"`
	CreatedTime    pgtype.Timestamptz `json:"created_time"`
	ModifiedTime   pgtype.Timestamptz `json:"modified_time"`
	ThumbnailLink  pgtype.Text        `json:"thumbnail_link"`
	PreviewLink    pgtype.Text        `json:"preview_link"`
	WebViewLink    pgtype.Text        `json:"web_view_link"`
	WebContentLink pgtype.Text        `json:"web_content_link"`
	LinkExpiresAt  pgtype.Timestamptz `json:"link_expires_at"`
}

const countFilesWithFilters = `-- name: CountFilesWithFilters :one
SELECT COUNT(*)
FROM   synced_items
       JOIN linked_account
       ON linked_account.id = synced_items.account_id
WHERE  linked_account.user_id = $1
       AND (NULLIF($2, '') IS NULL OR synced_items.parent_folder = $2)
       AND (NULLIF($3, '') IS NULL OR linked_account.provider = $3::provider_enum)
       AND (NULLIF($4, '') IS NULL OR synced_items.name ILIKE '%' || $4::TEXT || '%')
       AND (
         CASE
           WHEN $5::TEXT[] IS NULL OR COALESCE(array_length($5::TEXT[], 1), 0) = 0
           THEN (NULLIF($4, '') IS NULL OR synced_items.name ILIKE '%' || $4::TEXT || '%')
           ELSE synced_items.provider_file_id = ANY($5::TEXT[])
         END
)
`

type CountFilesWithFiltersParams struct {
	UserID          string      `json:"user_id"`
	ParentFolder    interface{} `json:"parent_folder"`
	Provider        interface{} `json:"provider"`
	Search          interface{} `json:"search"`
	ProviderFileIds []string    `json:"provider_file_ids"`
}

func (q *Queries) CountFilesWithFilters(ctx context.Context, arg CountFilesWithFiltersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesWithFilters,
		arg.UserID,
		arg.ParentFolder,
		arg.Provider,
		arg.Search,
		arg.ProviderFileIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConflictingItems = `-- name: DeleteConflictingItems :exec
DELETE FROM synced_items WHERE provider_file_id = ANY($1::TEXT[]) AND account_id = $2
`

type DeleteConflictingItemsParams struct {
	ProviderFileIds []string    `json:"provider_file_ids"`
	AccountID       pgtype.UUID `json:"account_id"`
}

func (q *Queries) DeleteConflictingItems(ctx context.Context, arg DeleteConflictingItemsParams) error {
	_, err := q.db.Exec(ctx, deleteConflictingItems, arg.ProviderFileIds, arg.AccountID)
	return err
}

const deleteSyncedItems = `-- name: DeleteSyncedItems :exec
DELETE FROM synced_items WHERE id = ANY($1::UUID[]) AND account_id = $2
`

type DeleteSyncedItemsParams struct {
	FileIds   []pgtype.UUID `json:"file_ids"`
	AccountID pgtype.UUID   `json:"account_id"`
}

func (q *Queries) DeleteSyncedItems(ctx context.Context, arg DeleteSyncedItemsParams) error {
	_, err := q.db.Exec(ctx, deleteSyncedItems, arg.FileIds, arg.AccountID)
	return err
}

const getProviderFileIds = `-- name: GetProviderFileIds :many
SELECT synced_items.id AS file_id, synced_items.provider_file_id, synced_items.path, linked_account.provider, linked_account.id AS account_id
FROM synced_items JOIN linked_account ON linked_account.id = synced_items.account_id
WHERE linked_account.user_id = $1 AND synced_items.id = ANY($2::UUID[]) AND synced_items.is_trashed = $3
`

type GetProviderFileIdsParams struct {
	UserID    string        `json:"user_id"`
	Ids       []pgtype.UUID `json:"ids"`
	IsTrashed pgtype.Bool   `json:"is_trashed"`
}

type GetProviderFileIdsRow struct {
	FileID         pgtype.UUID  `json:"file_id"`
	ProviderFileID string       `json:"provider_file_id"`
	Path           pgtype.Text  `json:"path"`
	Provider       ProviderEnum `json:"provider"`
	AccountID      pgtype.UUID  `json:"account_id"`
}

func (q *Queries) GetProviderFileIds(ctx context.Context, arg GetProviderFileIdsParams) ([]GetProviderFileIdsRow, error) {
	rows, err := q.db.Query(ctx, getProviderFileIds, arg.UserID, arg.Ids, arg.IsTrashed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProviderFileIdsRow{}
	for rows.Next() {
		var i GetProviderFileIdsRow
		if err := rows.Scan(
			&i.FileID,
			&i.ProviderFileID,
			&i.Path,
			&i.Provider,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncedItemByID = `-- name: GetSyncedItemByID :one
SELECT name, provider_file_id, is_folder, path FROM synced_items WHERE account_id = $1 AND id = $2
`

type GetSyncedItemByIDParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	ID        pgtype.UUID `json:"id"`
}

type GetSyncedItemByIDRow struct {
	Name           string      `json:"name"`
	ProviderFileID string      `json:"provider_file_id"`
	IsFolder       bool        `json:"is_folder"`
	Path           pgtype.Text `json:"path"`
}

func (q *Queries) GetSyncedItemByID(ctx context.Context, arg GetSyncedItemByIDParams) (GetSyncedItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getSyncedItemByID, arg.AccountID, arg.ID)
	var i GetSyncedItemByIDRow
	err := row.Scan(
		&i.Name,
		&i.ProviderFileID,
		&i.IsFolder,
		&i.Path,
	)
	return i, err
}

const getSyncedItems = `-- name: GetSyncedItems :many
SELECT synced_items.id,
       synced_items.name,
       synced_items.size,
       synced_items.is_folder,
       synced_items.is_trashed,
       synced_items.thumbnail_link,
       synced_items.preview_link,
       synced_items.web_view_link,
       synced_items.web_content_link,
       synced_items.modified_time,
       synced_items.owner_info
FROM   synced_items
       JOIN linked_account
         ON linked_account.id = synced_items.account_id
WHERE  linked_account.user_id = $1
       AND (NULLIF($2, '') IS NULL OR synced_items.parent_folder = $2)
       AND (NULLIF($3, '') IS NULL OR linked_account.provider = $3::provider_enum)
       AND (
         CASE
           WHEN $4::TEXT[] IS NULL OR COALESCE(array_length($4::TEXT[], 1), 0) = 0
           THEN (NULLIF($5, '') IS NULL OR synced_items.name ILIKE '%' || $5::TEXT || '%')
           ELSE synced_items.provider_file_id = ANY($4::TEXT[])
         END
       )
ORDER BY
       CASE
           WHEN $6 = 'file_name' AND $7 = 'asc' THEN synced_items.name
           ELSE NULL -- Explicitly return NULL when not sorting by this
       END ASC,
       CASE
           WHEN $6 = 'file_name' AND $7 = 'desc' THEN synced_items.name
           ELSE NULL
       END DESC,
       CASE
           WHEN $6 = 'size' AND $7 = 'asc' THEN synced_items.size
           ELSE NULL
       END ASC,
       CASE
           WHEN $6 = 'size' AND $7 = 'desc' THEN synced_items.size
           ELSE NULL
       END DESC,
       CASE
           WHEN $6 = 'modified_time' AND $7 = 'asc' THEN synced_items.modified_time::TIMESTAMPTZ
           ELSE NULL
       END ASC,
       CASE
           WHEN $6 = 'modified_time' AND $7 = 'desc' THEN synced_items.modified_time::TIMESTAMPTZ
           ELSE NULL
       END DESC,
       synced_items.modified_time DESC
LIMIT $9 OFFSET $8
`

type GetSyncedItemsParams struct {
	UserID          string      `json:"user_id"`
	ParentFolder    interface{} `json:"parent_folder"`
	Provider        interface{} `json:"provider"`
	ProviderFileIds []string    `json:"provider_file_ids"`
	Search          interface{} `json:"search"`
	SortOn          interface{} `json:"sort_on"`
	SortBy          interface{} `json:"sort_by"`
	OffsetBy        int32       `json:"offset_by"`
	LimitBy         int32       `json:"limit_by"`
}

type GetSyncedItemsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Size           int64              `json:"size"`
	IsFolder       bool               `json:"is_folder"`
	IsTrashed      pgtype.Bool        `json:"is_trashed"`
	ThumbnailLink  pgtype.Text        `json:"thumbnail_link"`
	PreviewLink    pgtype.Text        `json:"preview_link"`
	WebViewLink    pgtype.Text        `json:"web_view_link"`
	WebContentLink pgtype.Text        `json:"web_content_link"`
	ModifiedTime   pgtype.Timestamptz `json:"modified_time"`
	OwnerInfo      json.RawMessage    `json:"owner_info"`
}

func (q *Queries) GetSyncedItems(ctx context.Context, arg GetSyncedItemsParams) ([]GetSyncedItemsRow, error) {
	rows, err := q.db.Query(ctx, getSyncedItems,
		arg.UserID,
		arg.ParentFolder,
		arg.Provider,
		arg.ProviderFileIds,
		arg.Search,
		arg.SortOn,
		arg.SortBy,
		arg.OffsetBy,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSyncedItemsRow{}
	for rows.Next() {
		var i GetSyncedItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Size,
			&i.IsFolder,
			&i.IsTrashed,
			&i.ThumbnailLink,
			&i.PreviewLink,
			&i.WebViewLink,
			&i.WebContentLink,
			&i.ModifiedTime,
			&i.OwnerInfo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFileTrashed = `-- name: SetFileTrashed :exec
UPDATE synced_items SET is_trashed = true WHERE id = ANY($1::UUID[]) AND account_id = $2
`

type SetFileTrashedParams struct {
	FileIds   []pgtype.UUID `json:"file_ids"`
	AccountID pgtype.UUID   `json:"account_id"`
}

func (q *Queries) SetFileTrashed(ctx context.Context, arg SetFileTrashedParams) error {
	_, err := q.db.Exec(ctx, setFileTrashed, arg.FileIds, arg.AccountID)
	return err
}
