// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task_logs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addNewTaskLog = `-- name: AddNewTaskLog :exec
INSERT INTO task_logs (
    task_id, account_id, type, status, queue, params
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type AddNewTaskLogParams struct {
	TaskID    string         `json:"task_id"`
	AccountID pgtype.UUID    `json:"account_id"`
	Type      string         `json:"type"`
	Status    TaskStatusEnum `json:"status"`
	Queue     string         `json:"queue"`
	Params    []byte         `json:"params"`
}

func (q *Queries) AddNewTaskLog(ctx context.Context, arg AddNewTaskLogParams) error {
	_, err := q.db.Exec(ctx, addNewTaskLog,
		arg.TaskID,
		arg.AccountID,
		arg.Type,
		arg.Status,
		arg.Queue,
		arg.Params,
	)
	return err
}

const updateTaskLogFailed = `-- name: UpdateTaskLogFailed :exec
UPDATE task_logs SET
status = 'failed', error = $1
WHERE task_id = $2
`

type UpdateTaskLogFailedParams struct {
	Error  pgtype.Text `json:"error"`
	TaskID string      `json:"task_id"`
}

func (q *Queries) UpdateTaskLogFailed(ctx context.Context, arg UpdateTaskLogFailedParams) error {
	_, err := q.db.Exec(ctx, updateTaskLogFailed, arg.Error, arg.TaskID)
	return err
}

const updateTaskLogFinish = `-- name: UpdateTaskLogFinish :exec
UPDATE task_logs SET
status = 'succeeded', finished_at = $1
WHERE task_id = $2
`

type UpdateTaskLogFinishParams struct {
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	TaskID     string             `json:"task_id"`
}

func (q *Queries) UpdateTaskLogFinish(ctx context.Context, arg UpdateTaskLogFinishParams) error {
	_, err := q.db.Exec(ctx, updateTaskLogFinish, arg.FinishedAt, arg.TaskID)
	return err
}

const updateTaskLogRetryCount = `-- name: UpdateTaskLogRetryCount :exec
UPDATE task_logs SET
status = 'retrying', retries = $1
WHERE task_id = $2
`

type UpdateTaskLogRetryCountParams struct {
	Retries pgtype.Int4 `json:"retries"`
	TaskID  string      `json:"task_id"`
}

func (q *Queries) UpdateTaskLogRetryCount(ctx context.Context, arg UpdateTaskLogRetryCountParams) error {
	_, err := q.db.Exec(ctx, updateTaskLogRetryCount, arg.Retries, arg.TaskID)
	return err
}

const updateTaskLogStart = `-- name: UpdateTaskLogStart :exec
UPDATE task_logs SET 
status = 'processing', started_at = $1 
WHERE task_id = $2
`

type UpdateTaskLogStartParams struct {
	StartedAt pgtype.Timestamptz `json:"started_at"`
	TaskID    string             `json:"task_id"`
}

func (q *Queries) UpdateTaskLogStart(ctx context.Context, arg UpdateTaskLogStartParams) error {
	_, err := q.db.Exec(ctx, updateTaskLogStart, arg.StartedAt, arg.TaskID)
	return err
}
