// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jwk.sql

package repository

import (
	"context"
)

const getJWKSPublicKey = `-- name: GetJWKSPublicKey :one
SELECT public_key FROM jwks LIMIT 1
`

func (q *Queries) GetJWKSPublicKey(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getJWKSPublicKey)
	var public_key string
	err := row.Scan(&public_key)
	return public_key, err
}
