// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: linked_account.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAccountDetails = `-- name: AddAccountDetails :exec
INSERT INTO linked_account (
    user_id, provider, provider_user_id, access_token, refresh_token, token_type, expiry, email, name, avatar_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type AddAccountDetailsParams struct {
	UserID         string             `json:"user_id"`
	Provider       ProviderEnum       `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   pgtype.Text        `json:"refresh_token"`
	TokenType      pgtype.Text        `json:"token_type"`
	Expiry         pgtype.Timestamptz `json:"expiry"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) AddAccountDetails(ctx context.Context, arg AddAccountDetailsParams) error {
	_, err := q.db.Exec(ctx, addAccountDetails,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenType,
		arg.Expiry,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	return err
}
