// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           string
	Username     string
	FirstName    pgtype.Text
	LastName     pgtype.Text
	EmailAddress string
	Provider     string
	ImageUrl     string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
