// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package repository

import (
	"context"
)

const getJWKSPublicKey = `-- name: GetJWKSPublicKey :one
SELECT public_key FROM jwks LIMIT 1
`

func (q *Queries) GetJWKSPublicKey(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getJWKSPublicKey)
	var public_key string
	err := row.Scan(&public_key)
	return public_key, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, email_verified, image, created_at, updated_at FROM "user" WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
