// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package repository

import (
	"context"
)

const testQuery = `-- name: TestQuery :one
SELECT 123
`

func (q *Queries) TestQuery(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, testQuery)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
