// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, username, first_name, last_name, email_address, provider, image_url) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertUserParams struct {
	ID           string
	Username     string
	FirstName    pgtype.Text
	LastName     pgtype.Text
	EmailAddress string
	Provider     string
	ImageUrl     string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.EmailAddress,
		arg.Provider,
		arg.ImageUrl,
	)
	return err
}
