// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: synced_items.sql

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AddSyncedItemsParams struct {
	AccountID      pgtype.UUID        `json:"account_id"`
	ProviderFileID string             `json:"provider_file_id"`
	Name           string             `json:"name"`
	Extension      string             `json:"extension"`
	Size           int64              `json:"size"`
	MimeType       pgtype.Text        `json:"mime_type"`
	CreatedTime    pgtype.Timestamptz `json:"created_time"`
	ModifiedTime   pgtype.Timestamptz `json:"modified_time"`
	ThumbnailLink  pgtype.Text        `json:"thumbnail_link"`
	PreviewLink    pgtype.Text        `json:"preview_link"`
	WebViewLink    pgtype.Text        `json:"web_view_link"`
	WebContentLink pgtype.Text        `json:"web_content_link"`
	LinkExpiresAt  pgtype.Timestamptz `json:"link_expires_at"`
}
