name: Development CI

on:
    push:
        branches: dev
    pull_request: 
        branches: dev
        types: closed

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '^1.23'
            
            - name: Install Dependencies
              run: go mod tidy && go mod download
            
            - name: Build Application
              run: go build -o bin/cloudmesh cmd/main.go