name: Main CI

on:
    push:
        branches: main
    pull_request: 
        branches: main
        types: closed

jobs:
    build_and_push_docker_image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./backend

        steps:
            - uses: actions/checkout@v4
            
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                context: ./backend
                push: true
                file: ./backend/Dockerfile
                tags: |
                  ${{ secrets.DOCKERHUB_USERNAME }}/cloudmesh_backend:${{ github.sha }} 
                  ${{ secrets.DOCKERHUB_USERNAME }}/cloudmesh_backend:latest

    deploy:
      runs-on: ubuntu-latest
      needs:
        - build_and_push_docker_image
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: create env file
          run: echo "GIT_COMMIT_HASH=${{ github.sha }}" >> .env

        - name: Docker stack deploy
          uses: cssnr/stack-deploy-action@v1
          with:
            name: cloudmesh
            file: docker-stack.yml
            user: ${{ secrets.REMOTE_USER }}
            host: ${{ secrets.REMOTE_HOST }}
            ssh_key: ${{ secrets.REMOTE_SSH_KEY }}
            env_file: .env
            detach: true
