name: Staging CI

on:
    push:
        branches: stag
    pull_request: 
        branches: stag
        types: closed

jobs:
    build_and_push_docker_image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloudmesh_backend:stag-${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/cloudmesh_backend:stag-latest